version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: postgres-db
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_DB=h_loc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin@iscae
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
    driver: bridge
